/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patients;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CreateConsult extends javax.swing.JFrame {

    /**
     * Creates new form CreateConsult
     */
    int id_consulta;
    public CreateConsult(int id_consulta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_consulta = id_consulta;
        loadInfo(id_consulta);
    }
    
    private void loadInfo(int id_consulta) {
        ResultSet res = Conexion.Consulta(String.format("SELECT c.fecha, p.genero,"
                + "p.edad, p.fecha_nacimiento, p.primer_nombre, p.segundo_nombre,"
                + "p.primer_apellido, p.segundo_apellido, c.peso, c.estatura, c.presion, "
                + "c.frecuencia_cardiaca, c.temperatura, c.frecuencia_respiratoria, "
                + "c.saturacion, ROUND(c.indice_masa,2) as indice_masa "
                + "FROM pacientes p inner join consultas c on(c.id_paciente = p.id_paciente) "
                + "where id_consulta like '%s'", id_consulta));
        DateField.setText(DateField.getText()+java.time.LocalDate.now().toString());
        try {
            while (res.next()) {
                GenderField.setText(GenderField.getText()+res.getString("genero"));
                AgeField.setText(AgeField.getText()+res.getString("edad"));
                BirthField.setText(BirthField.getText()+res.getString("fecha_nacimiento"));
                NameField.setText(NameField.getText()+res.getString("primer_nombre")+" "+
                        res.getString("segundo_nombre")+" "+res.getString("primer_apellido")+" "+
                        res.getString("segundo_apellido"));
                WeightField.setText(WeightField.getText()+res.getString("peso"));
                HeightField.setText(HeightField.getText()+res.getString("estatura"));
                PresionField.setText(WeightField.getText()+res.getString("presion"));
                CFrequenceField.setText(CFrequenceField.getText()+res.getString("frecuencia_cardiaca"));
                TemperatureField.setText(TemperatureField.getText()+res.getString("temperatura"));
                RFrequenceField.setText(RFrequenceField.getText()+res.getString("frecuencia_respiratoria"));
                SaturationField.setText(SaturationField.getText()+res.getString("saturacion"));
                MassField.setText(MassField.getText()+res.getString("indice_masa"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PreCheck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MotivoArea = new javax.swing.JTextArea();
        DateField = new javax.swing.JLabel();
        NameField = new javax.swing.JLabel();
        GenderField = new javax.swing.JLabel();
        AgeField = new javax.swing.JLabel();
        BirthField = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrdenesArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MassField = new javax.swing.JLabel();
        PresionField = new javax.swing.JLabel();
        CFrequenceField = new javax.swing.JLabel();
        TemperatureField = new javax.swing.JLabel();
        RFrequenceField = new javax.swing.JLabel();
        SaturationField = new javax.swing.JLabel();
        HeightField = new javax.swing.JLabel();
        WeightField = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 500));

        MotivoArea.setColumns(20);
        MotivoArea.setRows(5);
        jScrollPane1.setViewportView(MotivoArea);

        DateField.setText("Fecha: ");

        NameField.setText("Nombre Completo: ");

        GenderField.setText("Genero: ");

        AgeField.setText("Edad: ");

        BirthField.setText("Fecha de Nacimiento: ");

        OrdenesArea.setColumns(20);
        OrdenesArea.setRows(5);
        jScrollPane2.setViewportView(OrdenesArea);

        jLabel6.setText("Motivo de Consulta");

        jLabel7.setText("Ordenes Medicas");

        MassField.setText("IMC: ");

        PresionField.setText("Presión: ");

        CFrequenceField.setText("F.C.: ");

        TemperatureField.setText("T°: ");

        RFrequenceField.setText("F.R.: ");

        SaturationField.setText("SPO2: ");

        HeightField.setText("Talla: ");

        WeightField.setText("Peso: ");

        SubmitButton.setBackground(new java.awt.Color(28, 158, 153));
        SubmitButton.setForeground(new java.awt.Color(250, 250, 250));
        SubmitButton.setText("Completar");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateField)
                                .addGap(18, 18, 18)
                                .addComponent(GenderField)
                                .addGap(18, 18, 18)
                                .addComponent(AgeField)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BirthField)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PresionField)
                                    .addGap(18, 18, 18)
                                    .addComponent(CFrequenceField)
                                    .addGap(18, 18, 18)
                                    .addComponent(TemperatureField)
                                    .addGap(25, 25, 25)
                                    .addComponent(RFrequenceField)
                                    .addGap(18, 18, 18)
                                    .addComponent(SaturationField)
                                    .addGap(18, 18, 18)
                                    .addComponent(MassField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NameField)
                                    .addGap(39, 39, 39)
                                    .addComponent(WeightField)
                                    .addGap(44, 44, 44)
                                    .addComponent(HeightField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateField)
                    .addComponent(GenderField)
                    .addComponent(AgeField)
                    .addComponent(BirthField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField)
                    .addComponent(WeightField)
                    .addComponent(HeightField))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PresionField)
                    .addComponent(CFrequenceField)
                    .addComponent(TemperatureField)
                    .addComponent(RFrequenceField)
                    .addComponent(SaturationField)
                    .addComponent(MassField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitButton)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            if (MotivoArea.getText().equals("") || OrdenesArea.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error: Favor terminar de llenar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Conexion.Execute(String.format("update consultas set motivo_consulta = '%s', "
                        + "ordenes_medicas = '%s', estado = 'DESPACHADO'"
                    + " where id_consulta = %s; ",MotivoArea.getText(), OrdenesArea.getText(), id_consulta));
                this.dispose();
                JOptionPane.showMessageDialog(null, "Consulta Despachada", "Desachado", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeField;
    private javax.swing.JLabel BirthField;
    private javax.swing.JLabel CFrequenceField;
    private javax.swing.JLabel DateField;
    private javax.swing.JLabel GenderField;
    private javax.swing.JLabel HeightField;
    private javax.swing.JLabel MassField;
    private javax.swing.JTextArea MotivoArea;
    private javax.swing.JLabel NameField;
    private javax.swing.JTextArea OrdenesArea;
    private javax.swing.JLabel PresionField;
    private javax.swing.JLabel RFrequenceField;
    private javax.swing.JLabel SaturationField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TemperatureField;
    private javax.swing.JLabel WeightField;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
